### ISSUE TITLE
Don't let Adminer under in Git version control

### ISSUE THREAD

**Issue by peter279k** [natanfelles/adminer-bootstrap-like#6]
As title, I think we don't let `Adminer` web App under the Git version control because we don't have to determine users which version they should use.

It should let users download this by themselves.

Perhaps it can add some informations in `README` to tell users what `Adminer` version can support this plugin.

**Comment by natanfelles** [comment]
The intention is to make this available as "plug and play", having the latest two Adminer versions.

Removing the Adminers could be great. But for this, this project will have to begin to have releases.

Until now, I simply was upgrading to the latest Adminer, and plugins, and fixing compatibility issues.

Also, some plugins are enabled by default.

Note that, the latest plugins can have incompatible changes with oldest versions.

Perhaps, just launch releases with Adminer version infos can solve it. And, this releases having the supported Adminer and plugin files, otherwise the user will must to search for them.

Some [plugins](https://github.com/pematon/adminer-plugins) are not official.

**Comment by peter279k** [comment]
@natanfelles, thank you for your reply. I hope we can release plugin version and remove `Adminer` from Git version control because it can let users select `Adminer` version and  this plugin friendly.

Maybe it can let this plugin have releases and composer support.

**Comment by natanfelles** [comment]
Please,  try the [develop](https://github.com/natanfelles/adminer-bootstrap-like/tree/develop) branch.
